FROM java:openjdk-8-jdk

ENV MAVEN_VERSION 3.3.9

RUN mkdir -p /usr/share/maven \
  && curl -fsSL http://apache.osuosl.org/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz \
    | tar -xzC /usr/share/maven --strip-components=1 \
  && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn

ENV MAVEN_HOME /usr/share/maven


COPY . /usr/src
WORKDIR /usr/src

RUN apt-get update && \
    apt-get install -y mysql-client

RUN curl -O http://ftp.cixug.es/apache/hadoop/common/hadoop-2.7.2/hadoop-2.7.2.tar.gz && \
    tar -xf hadoop-2.7.2.tar.gz && \
    mv hadoop-2.7.2 hadoop

RUN mvn clean && \
    mvn install -DskipTests

CMD tail -f /dev/null
